version: "3.8"

services:
  backend_blue:
    build: .
    container_name: backend_blue
    restart: always
    ports:
      - "3007:3006"

  backend_green:
    build: .
    container_name: backend_green
    restart: always
    ports:
      - "3008:3006"
